name: test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: fatJar
