name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This toolchain version should be aligned with the SurrealDB version
# See: https://github.com/surrealdb/surrealdb/blob/v3.0.4/rust-toolchain.toml
env:
  RUST_TOOLCHAIN: "1.91"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '21', '25' ]

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy,rustfmt

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2

      - name: Install dependencies
        run: sudo apt-get update

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build native lib
        run: cargo build

      - name: Start SurrealDB
        uses: surrealdb/setup-surreal@7c103070ba4f544240cd287432ba70d6f50163a5 # v2
        with:
          surrealdb_version: v3.0.4
          surrealdb_port: 8000
          surrealdb_auth: false
          surrealdb_strict: false
          surrealdb_log: info
          surrealdb_additional_args: --allow-all
          surrealdb_retry_count: 30

      - name: Test
        run: |
          chmod +x gradlew
          ./gradlew -i test jacocoTestReport
